"""Institution resolution: a curated override layer over the FIDIR-derived dataset (generated by
scripts/refresh_fidir.py). Exact normalized-name match only - overrides win. Pure, no DB."""
from app.integrations.statements.institutions import resolve_domain, resolve_institution, search


def test_override_wins_over_fidir():
    # FIDIR lists "Apple Card WC" (card.apple.com); the curated override maps the statement's
    # "Apple Card" ORG to apple.com and must take precedence.
    inst = resolve_institution("Apple Card")
    assert inst is not None and inst.domain == "apple.com"
    assert resolve_domain("apple card") == "apple.com"      # normalized, override path


def test_exact_name_match_from_dataset():
    inst = resolve_institution("American Express")
    assert inst is not None
    assert inst.name == "American Express" and inst.domain == "americanexpress.com"


def test_normalized_match_is_case_and_space_insensitive():
    assert resolve_domain("  WELLS   FARGO ") == "wellsfargo.com"


def test_unknown_org_returns_none():
    assert resolve_institution("Totally Not A Real Bank 12345") is None
    assert resolve_institution(None) is None
    assert resolve_domain("") is None


def test_no_substring_false_positives():
    # "Chase" is a real entry, but a longer ORG that merely contains it must NOT match (exact-only).
    assert resolve_institution("Chase Sapphire Imaginary Card") is None


def test_search_ranks_prefix_first_and_caps():
    results = search("amer", limit=5)
    assert results, "expected American Express et al."
    assert all("amer" in r.name.lower() for r in results)
    assert results[0].name.lower().startswith("amer")   # prefix outranks mid-string matches
    assert len(results) <= 5
    assert any(r.name == "American Express" and r.home_url for r in search("American Express"))


def test_search_empty_query_returns_nothing():
    assert search("") == [] and search("   ") == []


def test_override_variants_resolve_to_one_canonical():
    # Every known <ORG> spelling of an issuer must resolve to the SAME (name, domain) so an import never
    # splits one bank across two accounts (the "Apple Card" vs "Apple Card WC" duplicate).
    a = resolve_institution("Apple Card")
    b = resolve_institution("Apple Card WC")
    assert a is not None and b is not None
    assert (a.name, a.domain) == (b.name, b.domain) == ("Apple Card", "apple.com")


def test_search_has_no_duplicate_names():
    names = [i.name for i in search("bank", limit=100)]
    assert names, "expected FIDIR results for 'bank'"
    assert len(names) == len({n.lower() for n in names})   # de-duped by normalized name


if __name__ == "__main__":
    from tests._runner import run

    run(dict(globals()))
